//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFNetfluxProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.ActorRoles = new HashSet<ActorRole>();
            this.Favorites = new HashSet<Favorite>();
            this.FilmDetails = new HashSet<FilmDetail>();
        }
    
        public int Id { get; set; }
        public string Titel { get; set; }
        public byte[] Picture { get; set; }
        public string Genre { get; set; }
        public Nullable<double> Rating { get; set; }
        public Nullable<System.DateTime> Release { get; set; }
        public Nullable<System.DateTime> Expired { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActorRole> ActorRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite> Favorites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilmDetail> FilmDetails { get; set; }
    }
}
