//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFNetfluxProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmDetail
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> FilmId { get; set; }
        public Nullable<int> Playtime { get; set; }
    
        public virtual Film Film { get; set; }
    }
}
