//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFNetfluxProj
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class StreamingEntities : DbContext
    {
        public StreamingEntities()
            : base("name=StreamingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actor> Actors { get; set; }
        public virtual DbSet<ActorRole> ActorRoles { get; set; }
        public virtual DbSet<Favorite> Favorites { get; set; }
        public virtual DbSet<Film> Films { get; set; }
        public virtual DbSet<FilmDetail> FilmDetails { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
    
        public virtual ObjectResult<JoinActor_Result> JoinActor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<JoinActor_Result>("JoinActor");
        }
    
        public virtual ObjectResult<Joins_Result> Joins()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Joins_Result>("Joins");
        }
    
        public virtual ObjectResult<rightJoin_Result> rightJoin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rightJoin_Result>("rightJoin");
        }
    
        public virtual ObjectResult<SelectActorName_Result> SelectActorName(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectActorName_Result>("SelectActorName", nameParameter);
        }
    
        public virtual ObjectResult<SelectTopMovies_Result> SelectTopMovies()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectTopMovies_Result>("SelectTopMovies");
        }
    
        public virtual ObjectResult<UnionSelect_Result> UnionSelect()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UnionSelect_Result>("UnionSelect");
        }
    }
}
